import { ITemplatePayload } from "./interfaces";

interface ContactInquiryData {
  name: string;
  email: string;
  subject?: string;
  message: string;
  submittedAt?: string;
}

/**
 * Generates the HTML email sent to the inquiry receiver
 * whenever a visitor submits the Contact Us form.
 */
export function generateContactInquiryTemplate(
  data: ContactInquiryData
): ITemplatePayload {
  const { name, email, subject, message, submittedAt } = data;

  const displaySubject = subject?.trim() || "No subject";
  const displayDate =
    submittedAt ||
    new Date().toLocaleString("en-IN", {
      timeZone: "Asia/Kolkata",
      day: "2-digit",
      month: "short",
      year: "numeric",
      hour: "2-digit",
      minute: "2-digit",
    });

  // Sanitise message for safe HTML rendering
  const safeMessage = message
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/\n/g, "<br />");

  return {
    subject: `New Contact Request from ${name}`,
    text: [
      `New contact inquiry received on MotoXCode`,
      ``,
      `Name    : ${name}`,
      `Email   : ${email}`,
      `Subject : ${displaySubject}`,
      `Date    : ${displayDate}`,
      ``,
      `Message:`,
      message,
    ].join("\n"),
    html: `
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>New Contact Inquiry — MotoXCode</title>
  <style>
    body { margin: 0; padding: 0; background-color: #020617; font-family: Inter, 'Segoe UI', sans-serif; color: #f1f5f9; }
    .container { max-width: 560px; margin: 48px auto; background: #0f172a; border: 1px solid #1e293b; border-radius: 16px; overflow: hidden; }
    .header { background: linear-gradient(135deg, #1e293b 0%, #0f172a 100%); padding: 32px 36px; border-bottom: 1px solid #1e293b; }
    .brand { font-size: 20px; font-weight: 900; letter-spacing: 0.18em; text-transform: uppercase; color: #f8fafc; }
    .brand span { color: #ff5a1f; }
    .badge { display: inline-block; margin-top: 10px; background: #ff5a1f22; color: #ff5a1f; border: 1px solid #ff5a1f44; border-radius: 6px; font-size: 10px; font-weight: 700; letter-spacing: 0.15em; text-transform: uppercase; padding: 4px 10px; }
    .body { padding: 32px 36px; }
    .section-title { font-size: 10px; font-weight: 700; letter-spacing: 0.2em; text-transform: uppercase; color: #475569; margin-bottom: 16px; }
    .field { margin-bottom: 20px; }
    .field-label { font-size: 10px; font-weight: 700; letter-spacing: 0.15em; text-transform: uppercase; color: #64748b; margin-bottom: 4px; }
    .field-value { font-size: 14px; color: #e2e8f0; line-height: 1.5; }
    .field-value a { color: #ff5a1f; text-decoration: none; }
    .divider { height: 1px; background: #1e293b; margin: 24px 0; }
    .message-box { background: #020617; border: 1px solid #1e293b; border-radius: 10px; padding: 20px 22px; }
    .message-text { font-size: 14px; color: #cbd5e1; line-height: 1.7; }
    .footer { padding: 20px 36px; border-top: 1px solid #1e293b; text-align: center; }
    .footer-text { font-size: 11px; color: #334155; line-height: 1.6; }
    .reply-btn { display: inline-block; margin-top: 20px; background-color: #ff5a1f; color: #fff; text-decoration: none; font-weight: 700; font-size: 12px; letter-spacing: 0.1em; text-transform: uppercase; padding: 12px 28px; border-radius: 8px; }
  </style>
</head>
<body>
  <div class="container">
    <div class="header">
      <div class="brand">Moto<span>X</span>Code</div>
      <div class="badge">New Inquiry</div>
    </div>

    <div class="body">
      <p class="section-title">Sender Details</p>

      <div class="field">
        <div class="field-label">Name</div>
        <div class="field-value">${name}</div>
      </div>

      <div class="field">
        <div class="field-label">Email</div>
        <div class="field-value"><a href="mailto:${email}">${email}</a></div>
      </div>

      <div class="field">
        <div class="field-label">Subject</div>
        <div class="field-value">${displaySubject}</div>
      </div>

      <div class="field">
        <div class="field-label">Submitted</div>
        <div class="field-value">${displayDate}</div>
      </div>

      <div class="divider"></div>

      <p class="section-title">Message</p>
      <div class="message-box">
        <p class="message-text">${safeMessage}</p>
      </div>

      <div style="text-align: center; margin-top: 28px;">
        <a href="mailto:${email}?subject=Re: ${encodeURIComponent(displaySubject)}" class="reply-btn">
          Reply to ${name}
        </a>
      </div>
    </div>

    <div class="footer">
      <p class="footer-text">
        This email was automatically generated by the MotoXCode contact form.<br />
        Do not reply to this email — use the button above to reply directly to the sender.
      </p>
    </div>
  </div>
</body>
</html>
    `.trim(),
  };
}
